---
title: "Data manipulation"
author: "Amin Shirazi"
date: "4/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(caret)

```


```{r}
df.train <- train %>% select(- c(BOROUGH, NEIGHBORHOOD, BLOCK, LOT, EASE.MENT, ADDRESS, APARTMENT.NUMBER, SALE.DATE, TOTAL.UNITS, BUILDING.CLASS.AT.PRESENT, BUILDING.CLASS.CATEGORY, BUILDING.CLASS.AT.TIME.OF.SALE, TAX.CLASS.AT.PRESENT, TAX.CLASS.AT.TIME.OF.SALE)) 
df.test <- test %>% select(- c(BOROUGH, NEIGHBORHOOD,  BLOCK, LOT, EASE.MENT, ADDRESS, APARTMENT.NUMBER, SALE.DATE, TOTAL.UNITS, BUILDING.CLASS.AT.PRESENT, BUILDING.CLASS.CATEGORY, BUILDING.CLASS.AT.TIME.OF.SALE, TAX.CLASS.AT.PRESENT, TAX.CLASS.AT.TIME.OF.SALE))
```


## Training data
```{r}
train<- read.csv('../data/train.csv') 
test <- read.csv('../data/Queens Test Set.csv') %>% select( -X.1)
id<-test[ , "INDEX"]
test<- test %>% select(-INDEX)
names(train)
dim(train)
```





```{r}
rm.var <- c('BOROUGH',
            'NEIGHBORHOOD',
            'BLOCK', 
            'LOT', 
            'EASE.MENT', 
            'ADDRESS', 
            'APARTMENT.NUMBER',
            'TOTAL.UNITS'
            )

df.train <- train %>% select(- c(rm.var) )
df.test <- test %>% select(- c(rm.var))
```



## Data manipulation
For now, I did not make any changes on the factor variables, just keep them as they are
```{r}
d <- df.train %>%
   mutate(
         BUILDING.CLASS.CATEGORY = as.factor(BUILDING.CLASS.CATEGORY),
         BUILDING.CLASS.AT.PRESENT = as.factor(BUILDING.CLASS.AT.PRESENT),
         BUILDING.CLASS.AT.TIME.OF.SALE = as.factor(BUILDING.CLASS.AT.TIME.OF.SALE), 
         TAX.CLASS.AT.PRESENT = as.factor(TAX.CLASS.AT.PRESENT), 
         TAX.CLASS.AT.TIME.OF.SALE = as.factor(TAX.CLASS.AT.TIME.OF.SALE))

d<- d %>% select(- BUILDING.CLASS.AT.PRESENT, - TAX.CLASS.AT.TIME.OF.SALE, 
                  -BUILDING.CLASS.CATEGORY, 
                  -SALE.DATE)

d<-d[-which(d$YEAR.BUILT %>% is.na()), ]
names(d)
```

```{r, eval=FALSE}
fact<- df.train %>% select(BUILDING.CLASS.CATEGORY, TAX.CLASS.AT.PRESENT, BUILDING.CLASS.AT.PRESENT, 
                           BUILDING.CLASS.AT.TIME.OF.SALE, TAX.CLASS.AT.TIME.OF.SALE)
dmy <- dummyVars(" ~ .", data = fact)
trsf <- data.frame(predict(dmy, newdata = fact))

train.oh<-bind_cols(trsf, dt)
train.oh<- train.oh[-which(train.oh$YEAR.BUILT %>% is.na()), ]

```



```{r}
#Fit on 90% of train set
ctrl=trainControl(method="repeatedcv",repeats = 10,number=10)

lmtune<-train(SALE.PRICE ~ .,
              data=d, 
              method="lm",
              trControl=ctrl)

summary(lmtune)
# 0.4092

```


## Manipulation on test set
```{r}
dtest<- df.test %>%
  mutate(
    BUILDING.CLASS.CATEGORY = str_trim(BUILDING.CLASS.CATEGORY, 'both'), 
    BUILDING.CLASS.AT.PRESENT = str_trim(BUILDING.CLASS.AT.PRESENT, 'both'), 
    BUILDING.CLASS.AT.TIME.OF.SALE = str_trim(BUILDING.CLASS.AT.TIME.OF.SALE, 'both'), 
    TAX.CLASS.AT.PRESENT = str_trim(TAX.CLASS.AT.PRESENT, 'both'), 
    TAX.CLASS.AT.TIME.OF.SALE = str_trim(TAX.CLASS.AT.TIME.OF.SALE, 'both'), 
    SALE.DATE = str_trim(SALE.DATE, 'both')) %>% 
  mutate(
         BUILDING.CLASS.CATEGORY = as.factor(BUILDING.CLASS.CATEGORY),
         BUILDING.CLASS.AT.PRESENT = as.factor(BUILDING.CLASS.AT.PRESENT),
         BUILDING.CLASS.AT.TIME.OF.SALE = as.factor(BUILDING.CLASS.AT.TIME.OF.SALE), 
         TAX.CLASS.AT.PRESENT = as.factor(TAX.CLASS.AT.PRESENT), 
         TAX.CLASS.AT.TIME.OF.SALE = as.factor(TAX.CLASS.AT.TIME.OF.SALE), 
         LAND.SQUARE.FEET = log(as.numeric(as.factor(LAND.SQUARE.FEET))+1), 
         GROSS.SQUARE.FEET = log(as.numeric(as.factor(GROSS.SQUARE.FEET))+1)) %>% 
  select(- BUILDING.CLASS.AT.PRESENT, - TAX.CLASS.AT.TIME.OF.SALE, 
                  -BUILDING.CLASS.CATEGORY,  
         -SALE.DATE)

```



```{r}
fact<- df.test %>% select(BUILDING.CLASS.CATEGORY, TAX.CLASS.AT.PRESENT, BUILDING.CLASS.AT.PRESENT, 
                           BUILDING.CLASS.AT.TIME.OF.SALE, TAX.CLASS.AT.TIME.OF.SALE)
tt<- df.test %>% select(- BUILDING.CLASS.AT.PRESENT, - TAX.CLASS.AT.TIME.OF.SALE, 
                  - BUILDING.CLASS.AT.TIME.OF.SALE, -BUILDING.CLASS.CATEGORY, -TAX.CLASS.AT.PRESENT)
dmy <- dummyVars(" ~ .", data = fact)
trsf <- data.frame(predict(dmy, newdata = fact))

test.oh<-bind_cols(trsf, tt)
names(train.oh)
```



## Submission file
```{r}
#Predict on test
pred<-predict(lmtune, dtest)
pred<-exp(pred)
solution<-data.frame("INDEX"=id,"PRICE"= pred)
write.csv(solution, 
          paste0("../submission/solution", format(Sys.time(), "%d-%b-%Y %H.%M"), ".csv"), 
          row.names = FALSE)
```


```{r}
d$BUILDING.CLASS.AT.TIME.OF.SALE %>% levels()
dtest$BUILDING.CLASS.AT.TIME.OF.SALE %>% levels()
```




