---
title: "location"
author: "Amin Shirazi"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggmap)
```


```{r}
train<- read.csv('../data/train.csv') 
test <- read.csv('../data/test.csv')
```


## add lat and long to train data 

```{r}

# geo <- geocode(location = train$ADDRESS)
# df.geo <- bind_cols(train, geo)
# 
# ge.na<-df.geo %>% filter(lat %>% is.na()) 
# geo.na <- geocode(location = ge.na$NEIGHBORHOOD)
# 
# indx<-which(df.geo$lat %>% is.na())
# df.geo$lat[indx] <- geo.na$lat
# df.geo$lon[indx] <- geo.na$lon
# 
# write.csv(df.geo, "../data/train.csv")

```


```{r}
get_local_spot <-  get_map("Queens", maptype = "terrain", zoom = 11) 

ggmap(get_local_spot) + 
   geom_point(data = train, aes(x = lon, y = lat), color = "navy", size = 1) +
  ggtitle(label = "", subtitle = "Map of real estates in train data by zipcode")


ggmap(get_local_spot, extent = "device") + 
  stat_summary_2d(data = train, aes(x = lon, y = lat, z = SALE.PRICE), fun = mean, alpha = 0.6, bins = 30) + scale_fill_gradient(name = "Log Price", low = "green", high = "red")
```




## Add lat and long to test data
```{r}

# geo <- geocode(location = test$ADDRESS)
# 
# 
# df.geo <- bind_cols(test, geo)
# df.geo %>% summary()
# ge.na<-df.geo %>% filter(lat %>% is.na()) 
# geo.na <- geocode(location = ge.na$NEIGHBORHOOD)
# 
# indx<-which(df.geo$lat %>% is.na())
# df.geo$lat[indx] <- geo.na$lat
# df.geo$lon[indx] <- geo.na$lon

#write.csv(df.geo, "../data/test.csv")

```


```{r}
ggmap(get_local_spot) + 
   geom_point(data = test, aes(x = lon, y = lat), color = "navy", size = 1) +
  ggtitle(label = "", subtitle = "Map of real estates in test data by zipcode")

```

```{r}
train %>% ggplot(aes(lat)) + geom_boxplot()
train %>% ggplot(aes(lon)) + geom_boxplot()
```


```{r}
loc <- data.table::fread("./xgb/US.txt")
ny <- loc %>% filter(V4== "New York", V5=="NY") %>% select(V2, V10, V11)
ny.loc <- ny %>% filter(V6 =="Queens")
names(ny) <- c("ZIP.CODE", "Lat", "Long")

d = left_join(train, ny, by = "ZIP.CODE")
d %>% ggplot(aes(Lat)) + geom_boxplot()
d<- d %>% select(-lat, -lon)
names(d)[23:24]<- c("lat", "lon")
write.csv(d, "../data/train.csv")

```

```{r}
d = left_join(test, ny, by = "ZIP.CODE")
d<- d %>% select(-lat, -lon)
names(d)[24:25]<- c("lat", "lon")
write.csv(d, "../data/test.csv")
```

