---
title: "xgb"
author: "Amin Shirazi"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(caret)
library(magrittr)
require(xgboost)
library(stringr)
do.call_rbind_read.csv <- function(path, pattern = "*.csv") {
  files = list.files(path, pattern, full.names = TRUE)
  do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
}

```


```{r}
rm.var <- c(
            'BOROUGH',
            'NEIGHBORHOOD',
            'BLOCK', 
            'LOT', 
            'EASE.MENT', 
            'ADDRESS', 
            'APARTMENT.NUMBER',
            'TOTAL.UNITS', 
            "SALE.DATE"
            )
train <- read.csv('../data/train.csv')
train <- train %>% select(- all_of(rm.var))

test<- read.csv('../data/test.csv')
id<-test[ , "INDEX"]
test <- test %>% select(-INDEX, - all_of(rm.var))
```



```{r}
df.train <- train %>% 
  filter(!YEAR.BUILT %>% is.na()) %>% 
           mutate(YEAR.BUILT = as.double(YEAR.BUILT), 
                  year_cutoff = as.double(year_cutoff),
                   BUILDING.CLASS.CATEGORY = as.factor(BUILDING.CLASS.CATEGORY),
                   BUILDING.CLASS.AT.PRESENT = as.factor(BUILDING.CLASS.AT.PRESENT),
                   BUILDING.CLASS.AT.TIME.OF.SALE = as.factor(BUILDING.CLASS.AT.TIME.OF.SALE), 
                   TAX.CLASS.AT.PRESENT = as.factor(TAX.CLASS.AT.PRESENT), 
                   TAX.CLASS.AT.TIME.OF.SALE = as.factor(TAX.CLASS.AT.TIME.OF.SALE)) 
           
train.num  <- train %>%
            filter(!YEAR.BUILT %>% is.na()) %>% 
            select(-c(BUILDING.CLASS.CATEGORY, 
                      TAX.CLASS.AT.PRESENT, 
                      BUILDING.CLASS.AT.PRESENT, 
                      BUILDING.CLASS.AT.TIME.OF.SALE, 
                      TAX.CLASS.AT.TIME.OF.SALE)) %>% 
                      mutate(YEAR.BUILT = as.double(YEAR.BUILT), 
                             year_cutoff = as.double(year_cutoff)) 
dfact <- train %>%
            filter(!YEAR.BUILT %>% is.na()) %>% 
                            select(c(BUILDING.CLASS.CATEGORY, 
                            TAX.CLASS.AT.PRESENT, 
                            BUILDING.CLASS.AT.PRESENT, 
                            BUILDING.CLASS.AT.TIME.OF.SALE, 
                            TAX.CLASS.AT.TIME.OF.SALE)) %>% 
     mutate(
         BUILDING.CLASS.CATEGORY = as.factor(BUILDING.CLASS.CATEGORY),
         BUILDING.CLASS.AT.PRESENT = as.factor(BUILDING.CLASS.AT.PRESENT),
         BUILDING.CLASS.AT.TIME.OF.SALE = as.factor(BUILDING.CLASS.AT.TIME.OF.SALE), 
         TAX.CLASS.AT.PRESENT = as.factor(TAX.CLASS.AT.PRESENT), 
         TAX.CLASS.AT.TIME.OF.SALE = as.factor(TAX.CLASS.AT.TIME.OF.SALE))

dummy <- dummyVars(" ~ .", data=dfact)
newdata <- data.frame(predict(dummy, newdata = dfact))
train.oh <- bind_cols(newdata, train.num)

names(df.train)

```

```{r}
Numdf<-df.train

for (i in 1:15) {
  Numdf[,i]<-as.double(Numdf[,i])
}

nrounds = 1800
xgb_grid = expand.grid(
  nrounds = nrounds,
  max_depth = 8,
  eta = 0.01,
  gamma =  0.1, 
  colsample_bytree = 0.4,
  min_child_weight = 3,
  subsample = 1 
  
)



XGBTune<-train(y=Numdf[,12],
              x=Numdf[,-12],
              method="xgbTree",
              verbose=FALSE,
              tuneGrid = xgb_grid,
              trControl= trainControl(method="repeatedcv",repeats = 10, number=10 , allowParallel=TRUE))
saveRDS(XGBTune, "./xgb/XGBTune.rds")

```

## Results for xgb with Zip code
```{r}
res <- do.call_rbind_read.csv(path = "./xgb/with_zip/")


write.csv(res, './xgb/with_zip/res.csv')
a = res %>% arrange(desc(-RMSE)) %>% filter(RMSE < 0.378) %>%
  select(eta, max_depth, gamma, colsample_bytree, min_child_weight, subsample, nrounds) %>% 
  apply(2, unique) 

a$nrounds %>% sort()
xgb_grid
```

```{r}
xgbtune2 <- readRDS("./xgb/with_zip/xgbtune2.rds")
xgbtune3 <- readRDS("./xgb/with_zip/xgbtune3.rds")
xgbtune4 <- readRDS("./xgb/with_zip/xgbtune4.rds")
xgbtune5 <- readRDS("./xgb/with_zip/xgbtune5.rds")
xgbtune6 <- readRDS("./xgb/with_zip/xgbtune6.rds")
xgbtune7 <- readRDS("./xgb/with_zip/xgbtune7.rds")
xgbtune8 <- readRDS("./xgb/with_zip/xgbtune8.rds")
xgbtune9 <- readRDS("./xgb/with_zip/xgbtune9.rds")
xgbtune10 <- readRDS("./xgb/with_zip/xgbtune10.rds")
xgbtune11 <- readRDS("./xgb/with_zip/xgbtune11.rds")
xgbtune12 <- readRDS("./xgb/with_zip/xgbtune12.rds")
xgbtune13 <- readRDS("./xgb/with_zip/xgbtune13.rds")



grab_rmse<-function(tune){
  index<-which.min(tune$results$RMSE)
  tune$results[index,]$RMSE
}

all.tunes<-list(xgbtune2, xgbtune3, xgbtune4, xgbtune5, 
                xgbtune6, xgbtune7, xgbtune8, xgbtune9, xgbtune10, 
                xgbtune11, xgbtune12, xgbtune13)
all.RMSE<-lapply(all.tunes, grab_rmse)
all.RMSE
xgbtune2$bestTune
```

```{r}
df.test <- test %>% 
           mutate(YEAR.BUILT = as.double(YEAR.BUILT), 
                  year_cutoff = as.double(year_cutoff),
                   BUILDING.CLASS.CATEGORY = as.factor(BUILDING.CLASS.CATEGORY),
                   BUILDING.CLASS.AT.PRESENT = as.factor(BUILDING.CLASS.AT.PRESENT),
                   BUILDING.CLASS.AT.TIME.OF.SALE = as.factor(BUILDING.CLASS.AT.TIME.OF.SALE), 
                   TAX.CLASS.AT.PRESENT = as.factor(TAX.CLASS.AT.PRESENT), 
                   TAX.CLASS.AT.TIME.OF.SALE = as.factor(TAX.CLASS.AT.TIME.OF.SALE),
                   LAND.SQUARE.FEET = as.numeric(as.factor(LAND.SQUARE.FEET)), 
                   GROSS.SQUARE.FEET = as.numeric(as.factor(GROSS.SQUARE.FEET)))

```

```{r}
Numdf<-df.test

for (i in 1:15) {
  Numdf[,i]<-as.double(Numdf[,i])
}
pred<-predict(xgbtune2, Numdf) #df.test is the manipulated df of test 
pred<-(exp(pred) -1 )*1.085
solution<-data.frame("INDEX"=id,"PRICE"= pred)
write.csv(solution, 
          paste0("../submission/solution", format(Sys.time(), "%d-%b-%Y %H.%M"), "xgbtune2.csv"), 
          row.names = FALSE)
```


























